services:
  app-frontend:
    build:
      context: ./app-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app-frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge