services:
  app-frontend:
    build:
      context: ./app-frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
    restart: always

  app-backend:
    build:
      context: ./app-backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    restart: always

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - app-frontend
      - app-backend
    restart: always
