services:
  app-frontend:
    build:
      context: ./app-frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
    restart: always

  app-backend:
    build:
      context: ./app-backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    restart: always
  
  app-admin:
    build:
      context: ./app-admin
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    depends_on:
      - mongo
    environment:
      PORT: 3001
      DATABASE_URI: mongodb://aiep-admin:aiep2024!@mongo:27017
      PAYLOAD_SECRET: d1b8a0cf8777070cad101e1d
      PAYLOAD_PUBLIC_SERVER_URL: http://app-admin:3001
      NEXT_PUBLIC_SERVER_URL: http://app-admin:3001
      PAYLOAD_CONFIG_PATH: dist/payload.config.js
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: aiep-admin
      MONGO_INITDB_ROOT_PASSWORD: aiep2024!

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - app-frontend
      - app-admin
      - app-backend
    restart: always

volumes:
  data:
