version: '3'
services:
  app:
    build:
      context: ./app
    container_name: app
    restart: always
    ports:
      - "3000:3000"

  admin:
    build:
      context: ./admin
    container_name: admin
    restart: always
    ports:
      - "3001:3001"

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
      - admin
