services:
  app-frontend:
    build:
      context: ./app-frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    restart: always

  app-backend:
    build:
      context: ./app-backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    restart: always
  
  app-admin:
    build:
      context: ./app-admin
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    depends_on:
      - mongo
    environment:
      DATABASE_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - /etc/letsencrypt/live/a-iep.org:/etc/nginx/ssl/a-iep.org:ro
      - /etc/letsencrypt/live/www.a-iep.org:/etc/nginx/ssl/www.a-iep.org:ro
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - app-frontend
      - app-admin
      - app-backend
    environment:
      DOMAIN: ${DOMAIN}
    restart: always

volumes:
  data: