services:
  app-frontend:
    build:
      context: ./app-frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
    restart: always

  app-backend:
    build:
      context: ./app-backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    restart: always
  
  app-admin:
    build:
      context: ./app-admin
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    depends_on:
      - mongo
    environment:
      DATABASE_URI: mongodb://mongo:27017/payload
      NODE_ENV: production
      PAYLOAD_SECRET: e2346cdbc3f8f418fefacc39
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - app-frontend
      - app-backend
    restart: always

volumes:
  data:
