services:
  app-frontend:
    build:
      context: ./app-frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
    restart: always

  app-backend:
    build:
      context: ./app-backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    restart: always
  
  app-admin:
    build:
      context: ./app-admin
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    depends_on:
      - mongo
    environment:
      DATABASE_URI: mongodb://aiep-admin:aiep2024!@mongo:27017
      PAYLOAD_SECRET: 4b6b3cd7c5ae0133fd2e709a
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: aiep-admin
      MONGO_INITDB_ROOT_PASSWORD: aiep2024!

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - app-frontend
      - app-backend
    restart: always

volumes:
  data:
