FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN apt-get update && apt-get install -y poppler-utils gcc
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ ./app

CMD ["celery", "-A", "app.celery_config.celery_app", "worker", "--loglevel=info"]
